"""
generate_config.py
一般的な P/E ヘテロジニアス マルチコア (2 NUMA ノード x (Big core + Small core)) を
想定した Sniper 設定ファイルを、戦略・スレッド数ごとに動的生成する。

特定の実機 (例: Intel Core Ultra 9 285K) を忠実に再現するモデルではなく、
一般的な消費者向けハイブリッドCPU (Intel 12〜14世代, Apple M系, ARM big.LITTLE系)
のP/E周波数比(概ね1.2〜1.6倍)を参考にした、ふんわりとした想定モデルである点に注意。

トポロジ (物理):
  CPU  0- 3 : P-core (Big),   4.0 GHz, Node0
  CPU  4- 7 : E-core (Small), 3.0 GHz, Node0
  CPU  8-11 : P-core (Big),   4.0 GHz, Node1
  CPU 12-15 : E-core (Small), 3.0 GHz, Node1

NUMAレイテンシ設定:
  ローカルDRAM   : 60 ns (perf_model/dram/latency)
  リモートペナルティ: 帯域幅競合による自然な遅延 (bus モデル)
    → emesh_hop_counter は使用しない
    → P/E コアで hop_latency がサイクル数で異なる問題を回避
    → Jin (2022) と同じアプローチ

キャッシュサイズ (意図的に縮小 → DRAMアクセス頻度を増やす):
  L1-D  : 16 KB (実機 48KB の 1/3)
  L2    : P-core 512 KB / E-core 256 KB (実機の 1/4)
  L3    : 4 MB 共有 (実機 36MB の約 1/9)
  → Class A/W ではL3ミスが多発し、NUMA効果が明確に現れる

Sniper のコアは cpu_map の順に割り当てられる:
  simulated core i → ordered_cpus[i] の特性 (周波数・NUMA ノード)
"""

import os

P_CORES    = set(range(0, 4))  | set(range(8, 12))
E_CORES    = set(range(4, 8))  | set(range(12, 16))
NODE0_CPUs = set(range(0, 8))
NODE1_CPUs = set(range(8, 16))

P_FREQ = 4.0   # GHz
E_FREQ = 3.0   # GHz (消費者向けハイブリッドCPUの典型比 ~1.3倍に合わせて変更、旧1.0GHzから)

LOCAL_LATENCY_NS = 60   # ローカルDRAMアクセスレイテンシ

# キャッシュサイズ (KB) - 意図的縮小
L1D_KB_P = 16
L1D_KB_E = 16
L2_KB_P  = 512
L2_KB_E  = 256
L3_KB    = 4096   # 全コア共有


def _core_freq(cpu_id: int) -> float:
    return P_FREQ if cpu_id in P_CORES else E_FREQ


def _core_node(cpu_id: int) -> int:
    return 0 if cpu_id in NODE0_CPUs else 1


def _controllers_interleaving(cpu_map: list, num_threads: int) -> int:
    """
    Node0 スレッドが先頭グループ・Node1 が後続グループに並んだ場合の
    グループサイズ = DRAM controllers_interleaving。
    片ノードのみの場合は num_threads を返す (controller 1 個)。
    """
    active = cpu_map[:num_threads]
    n0 = sum(1 for c in active if c in NODE0_CPUs)
    n1 = num_threads - n0
    if n0 == 0 or n1 == 0:
        return num_threads
    return n0


def _reorder_by_node(cpu_map: list, num_threads: int) -> list:
    """
    Node0 スレッドを先・Node1 を後ろに安定ソートして返す。
    emesh の stop 割り当て (core i → stop i // concentration) と整合させる。
    """
    active = cpu_map[:num_threads]
    node0 = [c for c in active if c in NODE0_CPUs]
    node1 = [c for c in active if c in NODE1_CPUs]
    return node0 + node1


def generate_config(
    strategy: str,
    num_threads: int,
    cpu_map: list,
    output_path: str,
) -> str:
    """
    P/Eヘテロジニアス設定ファイルを生成して output_path に書き込み、パスを返す。
    """
    ordered_cpus = _reorder_by_node(cpu_map, num_threads)
    n_cores      = num_threads
    interleaving = _controllers_interleaving(cpu_map, num_threads)

    # Sniper要件: controllers_interleaving は shared_cores の倍数であること。
    # shared_cores = interleaving → L3グループがDRAMコントローラ境界に一致する。
    shared_cores = interleaving

    # per-core 周波数リスト (GHz)
    freqs = [_core_freq(c) for c in ordered_cpus]
    freq_str = ",".join(f"{f:.1f}" for f in freqs)

    # dispatch_width / window_size (P/E コア別)
    dispatch = [4 for _ in ordered_cpus]
    rob_size  = [224 if c in P_CORES else 128 for c in ordered_cpus]
    dispatch_str = ",".join(str(d) for d in dispatch)
    rob_str      = ",".join(str(r) for r in rob_size)

    # L1-D (KB)
    l1d_size = [L1D_KB_P if c in P_CORES else L1D_KB_E for c in ordered_cpus]
    l1d_str  = ",".join(str(s) for s in l1d_size)

    # L2 (KB)
    l2_size = [L2_KB_P if c in P_CORES else L2_KB_E for c in ordered_cpus]
    l2_str  = ",".join(str(s) for s in l2_size)

    cfg = f"""\
# Heterogeneous P/E core system - strategy={strategy}, threads={num_threads}
# Generated by ClaudeXSniper/config/generate_config.py
# Ordered CPUs: {ordered_cpus}
#
# NUMA penalty: bus model (bandwidth-contention-based, no fixed hop latency)
# Cache sizes : L1-D={L1D_KB_P}KB  L2(P)={L2_KB_P}KB L2(E)={L2_KB_E}KB  L3={L3_KB}KB

#include nehalem
#include gainestown

[general]
total_cores = {n_cores}
enable_icache_modeling = true

[perf_model/core]
type = interval
frequency = {P_FREQ:.1f}
frequency[] = {freq_str}

[perf_model/core/interval_timer]
dispatch_width = 4
dispatch_width[] = {dispatch_str}
window_size = 224
window_size[] = {rob_str}

[perf_model/l1_dcache]
cache_size = {L1D_KB_P}
cache_size[] = {l1d_str}

[perf_model/l2_cache]
cache_size = {L2_KB_P}
cache_size[] = {l2_str}
associativity = 8

[perf_model/l3_cache]
cache_size = {L3_KB}
associativity = 16
shared_cores = {shared_cores}

[perf_model/dram]
num_controllers = -1
controllers_interleaving = {interleaving}
latency = {LOCAL_LATENCY_NS}
per_controller_bandwidth = 51.2

[network]
memory_model_1 = bus
memory_model_2 = bus

[network/bus]
bandwidth = 102.4
ignore_local_traffic = true

[dvfs/simple]
cores_per_socket = {n_cores}

[power]
vdd = 1.0
technology_node = 10
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(cfg)

    return output_path


def get_config_path(
    output_dir: str, strategy: str, num_threads: int
) -> str:
    """設定ファイルの保存パスを返す（ファイルは生成しない）。"""
    return os.path.join(output_dir, f"arrow_lake_{strategy}_{num_threads}TH.cfg")
